#
# Rate limiting of expensive pages
#

# Get first two numbers of IPv4 address
map $remote_addr $mwrl_subnet {
	default "";
	"~^(?<subnet>\d+\.\d+)" $subnet;
}

# Only rate limit HEAD and GET requests
map $request_method $mwrl_method_match {
	default 0;
	"HEAD" 1;
	"GET" 1;
}

#
# Note: This assumes URIs as they appear in the MediaWiki UI.
#
# We don't try to match custom parameter order, such as:
#
#   ?oldid=X&action=edit
#
# Because a crawler would never see such a URI; it would only see:
#
#   ?action=edit&oldid=X
#
map $request_uri $mwrl_uri_match {

	# This regex is to allow specific index.php queries:
	#
	# * Searching: search= at start
	# * History page 1: title= at start, action=history at end
	# * Edit current rev: title= at start, action=edit at end (optional section/redlink)
	# * Registration & login: title=Special:(CreateAccount|UserLogin) at start
	#
	"~^/w/index\.php\?(search=|title=(.*&action=(history|edit(&section=[0-9a-z]+|&redlink=1)?)$|Special:(CreateAccount|UserLogin)))"
		0;

	# Also allow these specific /wiki/Special: calls
	"~^/wiki/Special:((All)?My|CreateAccount|UserLogin|PasswordReset|Captcha|Upload|EditPage)"
		0;

	# Limit all other /w/index.php and /wiki/Special: calls
	"~^(/w/index\.php|/wiki/Special:)" 1;

	# Allow everything else
	default 0;
}

# Only limit anonymous visitors
map $http_cookie $mwrl_is_anon {
	default 1;
	"~[a-z]UserID=" 0;
}

# Combine criteria to define key; empty means no rate limit
map $mwrl_method_match$mwrl_uri_match$mwrl_is_anon $mwrl_subnet_key {
	default "";
	"111"   $mwrl_subnet;
}
map $mwrl_method_match$mwrl_uri_match$mwrl_is_anon $mwrl_global_key {
	default "";
	"111"   "G";
}

# Note that a burst allowance is defined elsewhere
limit_req_zone $mwrl_subnet_key zone=mwrl_subnet:8m rate=10r/m;
limit_req_zone $mwrl_global_key zone=mwrl_global:1m rate=30r/s;

# Be honest to the client instead of faking 5xx
limit_req_status 429;

# If you don't want rate limiting to trigger error logs
#limit_req_log_level notice;
